services:
  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "5000:8080"
    networks:
      - project1_people-network

networks:
  project1_people-network:
    external: true